spring:
  application:
    name: @project.name@
  datasource:
    platform: h2
    url: jdbc:h2:file:~/.beehappy/beehappy_db;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate.ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migrations/${spring.datasource.platform}/customer

server:
  port: 8042

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs.path: /api-docs

logging.level.org.springframework.security: DEBUG
logging.level.org.springframework.security.web.FilterChainProxy: DEBUG
logging.level.org.springframework.web: DEBUG

management:
  endpoints:
    web.exposure.include: '*'
  endpoint:
    health.show-details: always