spring:
  application:
    name: @project.name@

server:
  port: 8042

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs.path: /api-docs

logging.level.org.springframework.security: DEBUG
logging.level.org.springframework.security.web.FilterChainProxy: DEBUG
logging.level.org.springframework.web: DEBUG

management:
  endpoints:
    web.exposure.include: '*'
  endpoint:
    health.show-details: always